# -*- coding: utf-8 -*-
"""opp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ktIOKDjQrqRqLaTtAk5C2WiW7Ch9qavK
"""

import streamlit as st
import tensorflow as tf
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing import image
import numpy as np
from PIL import Image
import os
import gdown
from tensorflow.keras.layers import Input, GlobalAveragePooling2D, Dense, Dropout
from tensorflow.keras.models import Model
from tensorflow.keras.applications import ResNet50
from tensorflow.keras import regularizers

# --- 1. Definisi Konstanta dan ID Drive ---

# ID file model Anda dari Google Drive
DRIVE_FILE_ID = '1bQZDudbODB-xh4G4Pgln_7rei4uUSQMu'

# Nama file model setelah diunduh
MODEL_PATH = 'model_trained_5class_resnet101-v1.hdf5'

IMG_WIDTH, IMG_HEIGHT = 128, 128

# Pemetaan kelas (sesuai dengan notebook Anda)
CLASS_NAMES = ['croissant', 'hamburger', 'pancakes', 'takoyaki', 'waffles']

# --- 2. Fungsi Pemuatan Model (Menangani Unduhan) ---

@st.cache_resource
def load_and_compile_model(model_path, drive_id):
    # Cek apakah file model sudah ada di sistem
    if not os.path.exists(model_path):
        st.info(f"Model '{model_path}' tidak ditemukan. Mengunduh dari Google Drive...")
        try:
            # Mengunduh file dari Google Drive menggunakan gdown
            # ID harus publik ("Anyone with the link")
            gdown.download(id=drive_id, output=model_path, quiet=False)
            st.success("Model berhasil diunduh!")
        except Exception as e:
            st.error(f"Gagal mengunduh model dari Drive. Pastikan ID dan izin akses 'Anyone with the link' sudah benar. Error: {e}")
            st.error(e)
            return None

    # Muat model Keras yang sudah ada atau baru diunduh
    # Gunakan compile=False karena hanya untuk inference/prediksi
    try:
        model = load_model(model_path, compile=False)
        return model
    except Exception as e:
        st.error(f"Gagal memuat model yang sudah diunduh. Error: {e}")
        return None


# --- 3. Fungsi Prediksi ---

def model_predict(img_path, model):
    """Memproses gambar dan melakukan prediksi."""

    # Memuat dan mengubah ukuran gambar
    img = image.load_img(img_path, target_size=(IMG_WIDTH, IMG_HEIGHT))

    # Mengubah gambar menjadi array numpy
    img_array = image.img_to_array(img)

    # Menambahkan dimensi batch (1, 128, 128, 3) dan normalisasi
    img_array = np.expand_dims(img_array, axis=0) / 255.0

    # Melakukan prediksi
    pred = model.predict(img_array, verbose=0)

    # Mendapatkan hasil
    index = np.argmax(pred)
    pred_value = CLASS_NAMES[index]
    confidence = pred[0][index] * 100

    return pred_value, confidence

# --- 4. Aplikasi Streamlit Utama ---

def main():
    st.set_page_config(page_title="Food Image Classifier (ResNet50)", layout="centered")
    st.title("🍔 Food Image Classifier Prototype")
    st.markdown("Model: **ResNet50 Fine-tuned**")
    st.markdown("---")

    # Pemuatan Model (dengan fungsi unduh otomatis)
    model = load_and_compile_model(MODEL_PATH, DRIVE_FILE_ID)

    if model is None:
        st.stop() # Hentikan aplikasi jika model gagal dimuat

    st.success("Model siap digunakan! Silakan unggah gambar.")

    # Lanjutkan dengan widget upload dan prediksi
    uploaded_file = st.file_uploader("Unggah gambar makanan...", type=["jpg", "jpeg", "png"])

    if uploaded_file is not None:
        image_to_predict = Image.open(uploaded_file)
        st.image(image_to_predict, caption='Gambar yang Diunggah', use_column_width=True)
        st.markdown("---")

        # Simpan file sementara untuk diproses
        temp_file_path = "temp_img.jpg"
        with open(temp_file_path, "wb") as f:
            f.write(uploaded_file.getbuffer())

        with st.spinner('Menganalisis gambar...'):
            predicted_class, confidence = model_predict(temp_file_path, model)

        # Hapus file sementara
        os.remove(temp_file_path)

        st.subheader("✅ Hasil Prediksi")

        emoji = "🏆" if confidence > 80 else "🤔"

        st.metric(
            label="Kelas Makanan",
            value=f"{predicted_class.upper()} {emoji}",
            delta=f"{confidence:.2f}% Confidence"
        )
        st.balloons()

if __name__ == '__main__':
    # Hapus baris berikut jika Anda menjalankan di Streamlit Cloud.
    # Baris ini hanya untuk mengatasi peringatan saat running di lingkungan non-Streamlit
    # if 'ScriptRunContext' not in str(type(st.empty())) and not os.environ.get('STREAMLIT_SERVER_RUN_ONCE'):
    #     main()
    # else:
    #     main()
    main()